FROM node:10
 
WORKDIR /app
 
ENV PATH /app/node_modules/.bin:$PATH
# Copies package.json and package-lock.json to Docker environment
COPY package.json ./
 
# Installs all node packages
RUN npm install
 
# Copies everything over to Docker environment
COPY . .
 
# Uses port which is used by the actual application
EXPOSE 3000
 
# Finally runs the application
CMD [ "npm", "start" ]